[[hooks]]
name="PreCommit"
create=true
relink=true

[[hooks]]
name="PrePush"
create=true
relink=true

[[hooks]]
name="PostApplyPatch"
create=true
relink=true

[[hooks]]
name="PostMerge"
create=true
relink=true
pull=false

[[hooks]]
name="PostRewrite"
create=true
relink=true

[[hooks]]
name="PreCommit"
create=true
relink=true

[[hooks]]
name="PostCheckout"
create=true
relink=true
